"""
Создаёт ROADMAP.md с полным планом развития продукта.
Запуск: python setup_roadmap.py
"""
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).parent
ROADMAP = BASE / "ROADMAP.md"

# Собираем контент по частям (без конфликтов с кавычками)
PARTS = []

PARTS.append("# 🗺 ROADMAP — AI-администратор для тату-мастеров")
PARTS.append("")
PARTS.append(f"**Дата создания:** {datetime.now().strftime('%d.%m.%Y')}")
PARTS.append("**Репозиторий:** https://github.com/jetsetartist-prog/tattoo-ai-assistant")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

PARTS.append("## 🎯 Цель продукта")
PARTS.append("")
PARTS.append("Превратить продукт из «набора скриптов в папке» в **SaaS-сервис**, где мастер:")
PARTS.append("1. Регистрируется по email")
PARTS.append("2. Вводит токен своей группы ВК")
PARTS.append("3. Нажимает «Подключить»")
PARTS.append("4. **Бот работает** в его группе")
PARTS.append("5. **Кабинет** — с его данными")
PARTS.append("6. **Оплата** — подписка")
PARTS.append("")
PARTS.append("**Формула:** «Мастер нажимает одну кнопку — и вся его онлайн-работа автоматизирована.»")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

PARTS.append("## 🏗 Архитектура")
PARTS.append("")
PARTS.append("```")
PARTS.append("┌─────────────────────────────────────────────┐")
PARTS.append("│              ВАШ ПРОДУКТ                    │")
PARTS.append("│      «AI-администратор для тату-мастеров»   │")
PARTS.append("└─────────────────────────────────────────────┘")
PARTS.append("                    │")
PARTS.append("        ┌───────────┼───────────┐")
PARTS.append("        ↓           ↓           ↓")
PARTS.append("   ┌────────┐ ┌────────┐ ┌────────┐")
PARTS.append("   │  BOT   │ │  CRM   │ │  SMM   │")
PARTS.append("   │  (AI)  │ │кабинет │ │планер  │")
PARTS.append("   └────────┘ └────────┘ └────────┘")
PARTS.append("        │           │           │")
PARTS.append("        └───────────┼───────────┘")
PARTS.append("                    ↓")
PARTS.append("        ┌───────────────────────┐")
PARTS.append("        │   МУЛЬТИТЕНАНТНОСТЬ   │")
PARTS.append("        └───────────────────────┘")
PARTS.append("                    │")
PARTS.append("                    ↓")
PARTS.append("        ┌───────────────────────┐")
PARTS.append("        │     АДАПТЕРЫ          │")
PARTS.append("        ├───────────────────────┤")
PARTS.append("        │  VK     ✅ (готов)    │")
PARTS.append("        │  TG     ⏳             │")
PARTS.append("        │  WA     ⏳ (для IL)   │")
PARTS.append("        │  IG     ⏳ (для IL)   │")
PARTS.append("        └───────────────────────┘")
PARTS.append("```")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# ЭТАП 1
PARTS.append("## 📋 Этапы")
PARTS.append("")
PARTS.append("### ЭТАП 1: Мультитенантность (фундамент SaaS) — 2 недели")
PARTS.append("")
PARTS.append("**Зачем:** без этого нельзя обслуживать нескольких мастеров.")
PARTS.append("")
PARTS.append("- [ ] Таблица `tenants` — email, пароль, VK-токен, group_id, план, срок")
PARTS.append("- [ ] Поле `tenant_id` во всех таблицах")
PARTS.append("- [ ] Все функции в `core/` принимают `tenant_id`")
PARTS.append("- [ ] Все маршруты фильтруют по `tenant_id`")
PARTS.append("- [ ] Миграция существующих данных на `tenant_id=1`")
PARTS.append("")

# ЭТАП 2
PARTS.append("### ЭТАП 2: Форма подключения ВК — 3–5 дней")
PARTS.append("")
PARTS.append("**Зачем:** «ввёл токен → бот работает».")
PARTS.append("")
PARTS.append("- [ ] Страница `/admin/connect` — визард")
PARTS.append("- [ ] Инструкция «Как получить токен ВК» со скриншотами")
PARTS.append("- [ ] Проверка токена через `groups.getById`")
PARTS.append("- [ ] Получение `group_id` и `name` группы")
PARTS.append("- [ ] Сохранение токена в БД")
PARTS.append("- [ ] Автозапуск бота для мастера")
PARTS.append("")

# ЭТАП 3
PARTS.append("### ЭТАП 3: Регистрация + Онбординг — 1 неделя")
PARTS.append("")
PARTS.append("- [ ] Страница `/register` — email + пароль")
PARTS.append("- [ ] Письмо с подтверждением")
PARTS.append("- [ ] Онбординг-визард (язык, имя, услуги, график, ВК)")
PARTS.append("- [ ] Автоопределение языка по браузеру")
PARTS.append("")

# ЭТАП 4
PARTS.append("### ЭТАП 4: SMM-планер — 2 недели")
PARTS.append("")
PARTS.append("- [ ] Модуль 1: Аудит группы ВК (13 пунктов)")
PARTS.append("- [ ] Модуль 2: Генератор контент-плана (20 постов)")
PARTS.append("- [ ] Модуль 3: AI-генерация постов")
PARTS.append("- [ ] Модуль 4: Автопубликация в VK")
PARTS.append("- [ ] Модуль 5: Сбор отзывов")
PARTS.append("- [ ] Модуль 6: Генератор объявлений VK Ads")
PARTS.append("- [ ] Модуль 7: Диагностика «Нет заявок»")
PARTS.append("- [ ] Модуль 8: Аналитика")
PARTS.append("")

# ЭТАП 5
PARTS.append("### ЭТАП 5: Telegram-адаптер — 1 неделя")
PARTS.append("")
PARTS.append("- [ ] `adapters/telegram_adapter.py` (~80 строк)")
PARTS.append("- [ ] Работает с тем же ядром")
PARTS.append("- [ ] Тест: тот же бот в Telegram")
PARTS.append("")

# ЭТАП 6
PARTS.append("### ЭТАП 6: Оплата / Подписка — 1 неделя")
PARTS.append("")
PARTS.append("- [ ] Тарифы: Free / Basic / Pro")
PARTS.append("- [ ] Страница `/admin/billing`")
PARTS.append("- [ ] Интеграция ЮKassa / Тинькофф")
PARTS.append("- [ ] Проверка срока подписки")
PARTS.append("- [ ] Email-напоминания")
PARTS.append("")

# ЭТАП 7
PARTS.append("### ЭТАП 7: Инфраструктура — 1 неделя")
PARTS.append("")
PARTS.append("- [ ] VPS (€5/мес)")
PARTS.append("- [ ] Домен")
PARTS.append("- [ ] PostgreSQL вместо SQLite")
PARTS.append("- [ ] Docker")
PARTS.append("- [ ] Nginx + HTTPS")
PARTS.append("- [ ] Supervisor")
PARTS.append("- [ ] Callback API")
PARTS.append("")

# ЭТАП 8
PARTS.append("### ЭТАП 8: WhatsApp/Instagram-адаптеры — 2–3 недели")
PARTS.append("")
PARTS.append("- [ ] WhatsApp Business API")
PARTS.append("- [ ] Instagram DM API")
PARTS.append("- [ ] Мультиязычность he/en")
PARTS.append("- [ ] Приём фото")
PARTS.append("- [ ] RTL для иврита")
PARTS.append("")

# ЭТАП 9
PARTS.append("### ЭТАП 9 (ПОЗЖЕ): TargetHunter-модуль — 2–3 недели")
PARTS.append("")
PARTS.append("**Только для России.**")
PARTS.append("")
PARTS.append("- [ ] Парсинг VK-аудиторий")
PARTS.append("- [ ] Сбор активных пользователей")
PARTS.append("- [ ] Экспорт ID для VK Ads")
PARTS.append("- [ ] Интеграция в SMM-планер")
PARTS.append("")
PARTS.append("**⚠️ Для Израиля/Запада не подходит** (Meta запрещает парсинг).")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

PARTS.append("## 🚫 Что НЕ делать")
PARTS.append("")
PARTS.append("**TargetHunter для Facebook/Instagram.** Meta запрещает парсинг аудиторий.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

PARTS.append("## 📊 Сравнение платформ")
PARTS.append("")
PARTS.append("| Платформа | Бот | Реклама | Парсинг |")
PARTS.append("|---|---|---|---|")
PARTS.append("| **VK** | ✅ | ✅ | ✅ Можно (ЭТАП 9) |")
PARTS.append("| **Telegram** | ✅ | ⚠️ TG Ads | ❌ |")
PARTS.append("| **Facebook/Instagram** | ✅ | ⚠️ AI-оптимизация | ❌ Запрещено |")
PARTS.append("| **WhatsApp** | ✅ | — | — |")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

PARTS.append("## 🎯 Приоритеты")
PARTS.append("")
PARTS.append("**Сейчас:**")
PARTS.append("1. ЭТАП 1 — Мультитенантность")
PARTS.append("2. ЭТАП 2 — Подключение ВК")
PARTS.append("")
PARTS.append("**После первых клиентов:**")
PARTS.append("3. ЭТАП 3 — Регистрация")
PARTS.append("4. ЭТАП 4 — SMM-планер")
PARTS.append("5. ЭТАП 6 — Оплата")
PARTS.append("")
PARTS.append("**Для Израиля:**")
PARTS.append("6. ЭТАП 8 — WhatsApp/Instagram")
PARTS.append("7. ЭТАП 5 — Telegram")
PARTS.append("")
PARTS.append("**Для России (опционально):**")
PARTS.append("8. ЭТАП 9 — TargetHunter")
PARTS.append("")

PARTS.append("---")
PARTS.append("")
PARTS.append("## 📌 Источники (обучение Ильи Ерёмина)")
PARTS.append("")
PARTS.append("- **Урок 1:** путь клиента, пост-знакомство, 50/50 портфолио/личность")
PARTS.append("- **Урок 2:** оформление группы, альбомы, сбор отзывов")
PARTS.append("- **Урок 3:** реклама VK Ads, диагностика «нет заявок»")
PARTS.append("- **Урок 4:** контент-план на 20 постов, время публикации")
PARTS.append("- **Продажи:** скрипты общения, обработка возражений")
PARTS.append("")
PARTS.append("**База:** 22 000 ID тату-мастеров ВК, 17 федеральных групп.")
PARTS.append("")

CONTENT = "\n".join(PARTS)


def main():
    if ROADMAP.exists():
        backup = ROADMAP.with_suffix(".md.bak")
        backup.write_text(ROADMAP.read_text(encoding='utf-8'), encoding='utf-8')
        print(f"📦 Бэкап: {backup.name}")

    ROADMAP.write_text(CONTENT, encoding='utf-8')

    print(f"✅ ROADMAP.md создан")
    print(f"   Размер: {len(CONTENT)} символов")
    print(f"   Строк: {CONTENT.count(chr(10))}")
    print(f"   Этапов: {CONTENT.count('### ЭТАП')}")


if __name__ == '__main__':
    main()