"""
Создаёт MAX_PRODUCT_SPEC.md — спецификацию нового продукта для России (МАКС).
Запуск: python setup_max_product.py
"""
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).parent
SPEC = BASE / "MAX_PRODUCT_SPEC.md"

PARTS = []

PARTS.append("# 📘 MAX PRODUCT SPEC — AI-администратор для мастеров (Россия, МАКС)")
PARTS.append("")
PARTS.append(f"**Дата создания:** {datetime.now().strftime('%d.%m.%Y')}")
PARTS.append(f"**Статус:** Draft v1.0")
PARTS.append(f"**Платформа:** МАКС (мессенджер)")
PARTS.append(f"**Рынок:** Россия")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 1. Цель
PARTS.append("## 🎯 1. Цель продукта")
PARTS.append("")
PARTS.append("**AI-администратор для мастеров-одиночек в сфере услуг.**")
PARTS.append("")
PARTS.append("Мастер не настраивает бота — он даёт боту данные (услуги, цены, FAQ),")
PARTS.append("а бот сам консультирует, записывает клиентов и ведёт CRM.")
PARTS.append("")
PARTS.append("**Формула:** «Мастер нажимает одну кнопку — и вся его онлайн-работа автоматизирована.»")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 2. Отличие от VK-бота
PARTS.append("## 🔄 2. Отличие от VK-бота (что переносим, что пишем заново)")
PARTS.append("")
PARTS.append("**Переносим (логика):**")
PARTS.append("- Архитектура `core/` + `adapters/`")
PARTS.append("- Логика слотов и бронирования")
PARTS.append("- CRM: клиенты, услуги, история")
PARTS.append("- AI-ассистент (промпты, контекст)")
PARTS.append("- Мультиязычность (пока только ru)")
PARTS.append("- Календарь, статистика, настройки")
PARTS.append("")
PARTS.append("**Пишем заново (транспорт):**")
PARTS.append("- Webhook вместо LongPoll")
PARTS.append("- FastAPI вместо Flask")
PARTS.append("- `max_adapter.py` вместо `vk_adapter.py`")
PARTS.append("- PostgreSQL вместо SQLite")
PARTS.append("- Мультитенантность с самого начала")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 3. Целевая аудитория
PARTS.append("## 👥 3. Целевая аудитория")
PARTS.append("")
PARTS.append("**Мастера-одиночки в России:**")
PARTS.append("- Парикмахеры")
PARTS.append("- Косметологи")
PARTS.append("- Мастера татуажа")
PARTS.append("- Мастера лазерной депиляции")
PARTS.append("- Мастера ногтевого сервиса")
PARTS.append("- Мастера по наращиванию ресниц и бровей")
PARTS.append("- Тату-мастера (как одна из ниш)")
PARTS.append("")
PARTS.append("**Не подходит:**")
PARTS.append("- Перекупы")
PARTS.append("- Магазины")
PARTS.append("- Крупные студии с администратором (пока)")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 4. Архитектура
PARTS.append("## 🏗 4. Архитектура")
PARTS.append("")
PARTS.append("```")
PARTS.append("┌─────────────────────────────────────────────┐")
PARTS.append("│              ЯДРО (core/)                    │")
PARTS.append("│  AI, CRM, слоты, booking, FAQ, настройки    │")
PARTS.append("│  Не знает про МАКС — работает с абстракциями │")
PARTS.append("└─────────────────────────────────────────────┘")
PARTS.append("                    ↑")
PARTS.append("                    │")
PARTS.append("┌─────────────────────────────────────────────┐")
PARTS.append("│         ADAPTER (adapters/max/)              │")
PARTS.append("│  Webhook, отправка, кнопки, вложения         │")
PARTS.append("└─────────────────────────────────────────────┘")
PARTS.append("                    ↑")
PARTS.append("                    │")
PARTS.append("┌─────────────────────────────────────────────┐")
PARTS.append("│              МАКС API                        │")
PARTS.append("│  Webhook, send_message, attachments          │")
PARTS.append("└─────────────────────────────────────────────┘")
PARTS.append("```")
PARTS.append("")
PARTS.append("**Ключевой принцип:** ядро **не знает**, что работает с МАКСом.")
PARTS.append("Оно работает с `MessageAdapter`, `IncomingMessage`, `Button`.")
PARTS.append("Позже можно добавить Telegram, WhatsApp, Instagram — без переписывания ядра.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 5. Стек
PARTS.append("## 🧰 5. Технический стек")
PARTS.append("")
PARTS.append("- **Python 3.11+**")
PARTS.append("- **FastAPI** — для Webhook-сервера МАКСа")
PARTS.append("- **Uvicorn** — ASGI-сервер")
PARTS.append("- **PostgreSQL** — основная БД (мультитенантность)")
PARTS.append("- **Redis** — кэш, сессии, очереди (опционально)")
PARTS.append("- **SQLAlchemy** — ORM")
PARTS.append("- **Alembic** — миграции БД")
PARTS.append("- **GigaChat** — AI-провайдер (для России)")
PARTS.append("- **Yandex SMTP** — email")
PARTS.append("- **Docker** — упаковка")
PARTS.append("- **Nginx** — reverse proxy + HTTPS")
PARTS.append("- **VPS** — хостинг (когда будет бюджет)")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 6. Структура БД
PARTS.append("## 🗄 6. Структура БД")
PARTS.append("")
PARTS.append("### Таблица `tenants` (мастера/аккаунты)")
PARTS.append("- `id`, `email`, `password_hash`")
PARTS.append("- `business_type` — тип бизнеса (только для шаблонов услуг)")
PARTS.append("- `language` — ru/he/en")
PARTS.append("- `currency` — RUB/ILS/USD")
PARTS.append("- `max_token`, `max_bot_id` — интеграция с МАКС")
PARTS.append("- `webhook_url` — для МАКСа")
PARTS.append("- `plan`, `plan_until` — подписка")
PARTS.append("- `is_active` — включён ли бот")
PARTS.append("")
PARTS.append("### Таблица `masters`")
PARTS.append("- `id`, `tenant_id`, `name`, `phone`, `email`")
PARTS.append("- `work_hours` — график работы (JSON)")
PARTS.append("")
PARTS.append("### Таблица `services`")
PARTS.append("- `id`, `tenant_id`, `name`")
PARTS.append("- `duration_minutes` — длительность")
PARTS.append("- `buffer_minutes` — перерыв (по умолчанию 0)")
PARTS.append("- `price_from`, `price_to` — диапазон цен")
PARTS.append("- `is_active`")
PARTS.append("")
PARTS.append("### Таблица `faq`")
PARTS.append("- `id`, `tenant_id`, `question`, `answer`")
PARTS.append("- `order` — порядок отображения")
PARTS.append("")
PARTS.append("### Таблица `settings`")
PARTS.append("- `id`, `tenant_id`, `key`, `value`")
PARTS.append("- Ключи: `cancellation_policy`, `address`, `map_url`, `deposit_info`")
PARTS.append("")
PARTS.append("### Таблица `clients`")
PARTS.append("- `id`, `tenant_id`, `name`, `phone`, `email`, `notes`")
PARTS.append("")
PARTS.append("### Таблица `bookings`")
PARTS.append("- `id`, `tenant_id`, `master_id`, `client_id`, `service_id`")
PARTS.append("- `date`, `time`, `duration`, `status`")
PARTS.append("- `source` — `online` / `manual`")
PARTS.append("- `notes`, `reference_image`")
PARTS.append("- `price`, `deposit`")
PARTS.append("")
PARTS.append("### Таблица `custom_slots`")
PARTS.append("- `id`, `tenant_id`, `master_id`, `date`, `time`")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 7. Модули
PARTS.append("## 🧩 7. Модули продукта")
PARTS.append("")
PARTS.append("### ✅ Делаем в MVP")
PARTS.append("1. **Бот в МАКСе** — приветствие, меню, запись, AI-консультации")
PARTS.append("2. **CRM** — клиенты, услуги, история визитов")
PARTS.append("3. **Календарь** — рабочая неделя, слоты, custom slots")
PARTS.append("4. **Настройки бота** — услуги, FAQ, правила (без конструкторов)")
PARTS.append("5. **Статистика** — визиты, выручка, загрузка")
PARTS.append("6. **Мультитенантность** — один сервер, много мастеров")
PARTS.append("7. **Авторизация** — email + пароль, Yandex SMTP")
PARTS.append("")
PARTS.append("### ⏳ Откладываем")
PARTS.append("- Пакеты услуг (мастера не любят)")
PARTS.append("- Групповые услуги (пока)")
PARTS.append("- Онлайн-оплата (СБП вручную)")
PARTS.append("- SMM-планер (следующий этап)")
PARTS.append("- TargetHunter (только для VK, не для МАКСа)")
PARTS.append("- Реклама в МАКСе (пока не автоматизируется)")
PARTS.append("")
PARTS.append("### ❌ НЕ делаем")
PARTS.append("- Конструктор ботов (мастер не должен настраивать)")
PARTS.append("- Инструкции для AI (мастер не пишет промпты)")
PARTS.append("- Парсинг аудиторий (нелегально)")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 8. Интеграция с МАКС
PARTS.append("## 📱 8. Интеграция с МАКС")
PARTS.append("")
PARTS.append("**Платформа для партнёров:** `platform-api2.max.ru`")
PARTS.append("")
PARTS.append("**Архитектура:** Webhook (не LongPoll)")
PARTS.append("- МАКС присылает события на ваш URL")
PARTS.append("- Вы отвечаете через `POST /messages`")
PARTS.append("")
PARTS.append("**Требования:**")
PARTS.append("- HTTPS обязателен")
PARTS.append("- Публичный домен")
PARTS.append("- Модерация бота")
PARTS.append("")
PARTS.append("**Для мастера:**")
PARTS.append("1. Регистрация на Платформе для партнёров МАКС")
PARTS.append("2. Создание бота")
PARTS.append("3. Прохождение модерации")
PARTS.append("4. Получение токена")
PARTS.append("5. Ввод токена в кабинете → бот работает")
PARTS.append("")
PARTS.append("**Лимиты:**")
PARTS.append("- Самозанятые — до 2 ботов")
PARTS.append("- ИП/юрлица — до 5 ботов")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 9. Настройки бота
PARTS.append("## ⚙️ 9. Настройки бота (без конструкторов)")
PARTS.append("")
PARTS.append("Мастер заходит в кабинет (с телефона) и видит **три блока**:")
PARTS.append("")
PARTS.append("### Блок 1: «Услуги» (таблица)")
PARTS.append("| Название | Длительность | Цена от | Цена до |")
PARTS.append("|---|---|---|---|")
PARTS.append("| Восковая депиляция | 30 мин | 1500 | 2500 |")
PARTS.append("| Татуаж бровей | 2 ч | 8000 | 12000 |")
PARTS.append("")
PARTS.append("### Блок 2: «Частые вопросы» (список)")
PARTS.append("| Вопрос | Ответ |")
PARTS.append("|---|---|")
PARTS.append("| Как подготовиться? | Не пить кофе за 2 часа... |")
PARTS.append("| Это больно? | Используем анестезию... |")
PARTS.append("")
PARTS.append("### Блок 3: «Правила» (текст)")
PARTS.append("- Депозит: 1000₽")
PARTS.append("- Отмена: за 24 часа")
PARTS.append("- Адрес: ...")
PARTS.append("- Карта: ссылка")
PARTS.append("")
PARTS.append("**Мастер НЕ пишет:** «как бот должен отвечать», «инструкции для AI».")
PARTS.append("Он только **даёт данные** — бот сам решает, как их использовать.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 10. Универсальность
PARTS.append("## 🔀 10. Универсальность (business_type)")
PARTS.append("")
PARTS.append("**`business_type` нужен только для:**")
PARTS.append("- Подстановки шаблонов услуг при регистрации")
PARTS.append("- Промпта AI («Ты ассистент косметолога»)")
PARTS.append("- Названий в интерфейсе (опционально)")
PARTS.append("")
PARTS.append("**Логика записи, слотов, CRM — универсальна.**")
PARTS.append("Мастер сам прописывает услуги: сегодня «восковая депиляция»,")
PARTS.append("завтра «татуаж бровей» — без изменения кода.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 11. Российская специфика
PARTS.append("## 🇷🇺 11. Российская специфика")
PARTS.append("")
PARTS.append("- **Онлайн-оплата:** не критична. Мастера используют **СБП по номеру телефона**.")
PARTS.append("- **Касса и терминал:** не у всех. Не требуем.")
PARTS.append("- **Отчётность:** минимальная.")
PARTS.append("- **Язык:** только ru (пока).")
PARTS.append("- **Валюта:** RUB.")
PARTS.append("- **AI:** GigaChat (бесплатно для России).")
PARTS.append("- **Email:** Yandex SMTP.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 12. План разработки
PARTS.append("## 📋 12. План разработки")
PARTS.append("")
PARTS.append("### ЭТАП 1: Фундамент (2 недели)")
PARTS.append("- [ ] Структура проекта (core + adapters/max)")
PARTS.append("- [ ] FastAPI + Webhook")
PARTS.append("- [ ] PostgreSQL + SQLAlchemy + Alembic")
PARTS.append("- [ ] Таблица `tenants`, `masters`, `services`, `faq`, `settings`")
PARTS.append("- [ ] Мультитенантность")
PARTS.append("")
PARTS.append("### ЭТАП 2: МАКС-бот (1 неделя)")
PARTS.append("- [ ] `max_adapter.py`")
PARTS.append("- [ ] Приём Webhook-событий")
PARTS.append("- [ ] Отправка сообщений")
PARTS.append("- [ ] Кнопки, меню")
PARTS.append("")
PARTS.append("### ЭТАП 3: CRM + Календарь (2 недели)")
PARTS.append("- [ ] Слоты, бронирование")
PARTS.append("- [ ] Custom slots")
PARTS.append("- [ ] Кабинет мастера")
PARTS.append("- [ ] Авторизация")
PARTS.append("")
PARTS.append("### ЭТАП 4: AI-ассистент (1 неделя)")
PARTS.append("- [ ] GigaChat")
PARTS.append("- [ ] Консультации по FAQ")
PARTS.append("- [ ] Контекст диалога")
PARTS.append("")
PARTS.append("### ЭТАП 5: Настройки бота (1 неделя)")
PARTS.append("- [ ] Услуги (CRUD)")
PARTS.append("- [ ] FAQ (CRUD)")
PARTS.append("- [ ] Правила")
PARTS.append("")
PARTS.append("### ЭТАП 6: Инфраструктура (1 неделя)")
PARTS.append("- [ ] VPS + домен")
PARTS.append("- [ ] HTTPS")
PARTS.append("- [ ] Docker")
PARTS.append("- [ ] Nginx")
PARTS.append("- [ ] Supervisor")
PARTS.append("")
PARTS.append("### ЭТАП 7: Подписка (1 неделя)")
PARTS.append("- [ ] Тарифы")
PARTS.append("- [ ] Оплата (ЮKassa / Тинькофф)")
PARTS.append("- [ ] Проверка срока")
PARTS.append("")
PARTS.append("**Итого:** ~9 недель до готового MVP.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 13. Что НЕ делаем
PARTS.append("## 🚫 13. Что НЕ делаем")
PARTS.append("")
PARTS.append("- Пакеты услуг (мастера не любят скидки)")
PARTS.append("- Групповые услуги (пока)")
PARTS.append("- Конструктор ботов")
PARTS.append("- Инструкции для AI от мастера")
PARTS.append("- TargetHunter (только VK, не МАКС)")
PARTS.append("- Реклама в МАКСе (пока не автоматизируется)")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 14. Инфраструктура
PARTS.append("## ☁️ 14. Инфраструктура")
PARTS.append("")
PARTS.append("**Для разработки:** локально (ПК) + CloudPub для демо.")
PARTS.append("")
PARTS.append("**Для production:**")
PARTS.append("- VPS (Hetzner, Timeweb, Selectel) — от 500₽/мес")
PARTS.append("- Домен — от 1000₽/год")
PARTS.append("- HTTPS — Let's Encrypt (бесплатно)")
PARTS.append("- Docker + Nginx + Supervisor")
PARTS.append("- PostgreSQL (managed или на VPS)")
PARTS.append("")
PARTS.append("**Важно:** МАКС требует **публичный HTTPS** для Webhook.")
PARTS.append("Без VPS бот не заработает в production.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# 15. Открытые вопросы
PARTS.append("## ❓ 15. Открытые вопросы")
PARTS.append("")
PARTS.append("- [ ] Делаем ли **Telegram-адаптер** параллельно с МАКСом?")
PARTS.append("- [ ] Нужна ли **мультиязычность** (he/en) на старте?")
PARTS.append("- [ ] Делаем ли **SMM-планер** в MVP или отдельным этапом?")
PARTS.append("- [ ] Как обрабатывать **повторные визиты** (напоминания)?")
PARTS.append("- [ ] Нужны ли **фото работ** в боте?")
PARTS.append("- [ ] Как масштабировать на 100+ мастеров (Callback API vs Webhook per tenant)?")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# Как работать с документом
PARTS.append("## 📖 Как работать с этим документом")
PARTS.append("")
PARTS.append("### При старте нового чата")
PARTS.append("1. Скиньте **этот файл** первым сообщением.")
PARTS.append("2. Напишите: «Продолжаем MAX PRODUCT. С чего начнём?»")
PARTS.append("3. Ассистент прочитает и поймёт контекст.")
PARTS.append("")
PARTS.append("### При изменении решений")
PARTS.append("1. Обновите соответствующий раздел в этом файле.")
PARTS.append("2. Добавьте запись в **раздел 16 (История изменений)**.")
PARTS.append("3. Закоммитьте в Git.")
PARTS.append("")
PARTS.append("### Если что-то потерялось")
PARTS.append("- Откройте этот файл — там все решения.")
PARTS.append("- Если решения нет — задайте вопрос в чате.")
PARTS.append("- После ответа — **добавьте в файл**, чтобы не потерять.")
PARTS.append("")
PARTS.append("---")
PARTS.append("")

# История
PARTS.append("## 📝 16. История изменений")
PARTS.append("")
PARTS.append(f"### {datetime.now().strftime('%d.%m.%Y')} — Создание документа")
PARTS.append("- Определена цель продукта")
PARTS.append("- Определена платформа (МАКС, только Россия)")
PARTS.append("- Определён стек (FastAPI + PostgreSQL)")
PARTS.append("- Определена архитектура (core + adapters)")
PARTS.append("- Определена аудитория (мастера-одиночки, все ниши)")
PARTS.append("- Определено, что НЕ делаем")
PARTS.append("")

CONTENT = "\n".join(PARTS)


def main():
    if SPEC.exists():
        backup = SPEC.with_suffix(".md.bak")
        backup.write_text(SPEC.read_text(encoding='utf-8'), encoding='utf-8')
        print(f"📦 Бэкап: {backup.name}")

    SPEC.write_text(CONTENT, encoding='utf-8')

    print(f"✅ MAX_PRODUCT_SPEC.md создан")
    print(f"   Размер: {len(CONTENT)} символов")
    print(f"   Строк: {CONTENT.count(chr(10))}")
    print(f"   Разделов: {CONTENT.count('## ')}")


if __name__ == '__main__':
    main()